INSERT INTO cliente VALUES (DEFAULT, 'Anderson', 'anderson@camel.com', '123', '12365478908', '81985267452');
INSERT INTO cliente VALUES (DEFAULT, 'Elias', 'elais@camel.com', '123', '12318278906', '81985951452');
INSERT INTO cliente VALUES (DEFAULT, 'Ricardo', 'ricardo@camel.com', '123', '35765478980', '81936467452');
INSERT INTO cliente VALUES (DEFAULT, 'Helena', 'helena@camel.com', '123', '12365479551', '81985267842');
INSERT INTO cliente VALUES (DEFAULT, 'Luiz', 'luiz@camel.com', '123', '12365842960', '81985263202');
INSERT INTO cliente VALUES (DEFAULT, 'Vinícius', 'vinicius@camel.com', '123', '18242547890', '81985467452');
INSERT INTO cliente VALUES (DEFAULT, 'Claudia', 'claudia@camel.com', '123', '12825148420', '81985354452');
INSERT INTO cliente VALUES (DEFAULT, 'Marcela', 'marcela@camel.com', '123', '12365437890', '81985842452');
INSERT INTO cliente VALUES (DEFAULT, 'Paula', 'paula@camel.com', '123', '12345478910', '81985268422');
INSERT INTO cliente VALUES (DEFAULT, 'Michele', 'michele@camel.com', '123', '12348477890', '81946267452');

INSERT INTO endereco VALUES (DEFAULT, 1, '55042040', '15 de novembro', 'José Carlos de Oliveira', 85,'-','Caruaru','PE');
INSERT INTO endereco VALUES (DEFAULT, 2, '55853040', 'Rio Branco', 'Salgado', 98,'prox a padaria X','Bezerros','PE');
INSERT INTO endereco VALUES (DEFAULT, 3, '55042841', 'Treze de maio', 'Rendeiras', 482,'-','Caruaru','PE');
INSERT INTO endereco VALUES (DEFAULT, 4, '55048420', 'São Sebastião', 'Vila Kennedy', 36,'Proximo a farmácia Y','Recife','PE');
INSERT INTO endereco VALUES (DEFAULT, 5, '55087440', 'Cleto Campelo', 'Indianópolis', 84,'-','Caruaru','PE');
INSERT INTO endereco VALUES (DEFAULT, 6, '55843040', 'Adjair Casé', 'Divinópoles', 852,'Proximo a praça Z','Recife','PE');
INSERT INTO endereco VALUES (DEFAULT, 7, '55356040', 'Alferes jorge', 'Riachão', 357,'-','Bonito','PE');
INSERT INTO endereco VALUES (DEFAULT, 8, '55845640', 'Agamenon Magalhães', 'Centro', 185,'Segundo andar','Bezerros','PE');
INSERT INTO endereco VALUES (DEFAULT, 9, '55955640', 'Vigario Freire', 'Centro', 885,'-','São Caetano','PE');
INSERT INTO endereco VALUES (DEFAULT, 10, '55955980', 'Lourial José da Silva', 'Vila Kennedy', 175,'Próximo ao mercado Y','São Caetano','PE');

INSERT INTO categoria VALUES(DEFAULT, 'Fios e Cabos');
INSERT INTO categoria VALUES(DEFAULT, 'Iluminação');
INSERT INTO categoria VALUES(DEFAULT, 'Segunraça');
INSERT INTO categoria VALUES(DEFAULT, 'Tomadas e Interruptores');
INSERT INTO categoria VALUES(DEFAULT, 'Energia Solar');
INSERT INTO categoria VALUES(DEFAULT, 'Acessórios e Conexões');
INSERT INTO categoria VALUES(DEFAULT, 'Adaptadores e plugs');
INSERT INTO categoria VALUES(DEFAULT, 'Resistências');
INSERT INTO categoria VALUES(DEFAULT, 'Transformadores');
INSERT INTO categoria VALUES(DEFAULT, 'Contactores');

INSERT INTO subcategoria VALUES(DEFAULT, 1, 'Fio');
INSERT INTO subcategoria VALUES(DEFAULT, 1, 'Cabo');
INSERT INTO subcategoria VALUES(DEFAULT, 2, 'Luz');
INSERT INTO subcategoria VALUES(DEFAULT, 2, 'Lâmpada');
INSERT INTO subcategoria VALUES(DEFAULT, 3, 'Luva');
INSERT INTO subcategoria VALUES(DEFAULT, 3, 'Capacetes');
INSERT INTO subcategoria VALUES(DEFAULT, 4, 'Tomadas');
INSERT INTO subcategoria VALUES(DEFAULT, 4, 'Interruptores');
INSERT INTO subcategoria VALUES(DEFAULT, 5, 'Placa Solar');
INSERT INTO subcategoria VALUES(DEFAULT, 5, 'Luminaria Solar');
INSERT INTO subcategoria VALUES(DEFAULT, 6, 'Passa Fios');
INSERT INTO subcategoria VALUES(DEFAULT, 6, 'Conectores');
INSERT INTO subcategoria VALUES(DEFAULT, 7, 'Beijamin ou T');
INSERT INTO subcategoria VALUES(DEFAULT, 7, 'Plug Macho');
INSERT INTO subcategoria VALUES(DEFAULT, 7, 'Plug Fêmea');
INSERT INTO subcategoria VALUES(DEFAULT, 8, 'Para Chuveiro');
INSERT INTO subcategoria VALUES(DEFAULT, 9, 'Autotransformadores de Tensão');
INSERT INTO subcategoria VALUES(DEFAULT, 9, 'Inversor de Tenão');

INSERT INTO produto VALUES (DEFAULT, 'Interuptor', 5.09, 'O Interruptor Tramontina Lux2 1 Seção Simples 10A, foi desenvolvido para proporcionar mais praticidade e segurança no acionamento de energia elétrica.','Tramontina', true, 4);
INSERT INTO produto VALUES (DEFAULT, 'Tomada', 5.19, 'A Tomada Tramontina Lux2 1 Seção 2PxT 20A, foi desenvolvida para proporcionar maior qualidade e segurança como tomada de acionamento e alimentação elétrica.', 'Tramontina', false, 4);
INSERT INTO produto VALUES (DEFAULT, 'Fio', 179.90, 'O Cabo Flexível 2,5MM 100 Metros Azul SIL Fios é um cabo elétrico para instalações fixas em baixa tensão (residencias, comerciais e industriais)', 'Sil', true, 1);
INSERT INTO produto VALUES (DEFAULT, 'Lâmpada LED', 5.39, 'A lâmpada LED a-60 da nitrolux é ideal para iluminação interna. Podendo substituir modelos de lâmpada incandescente com gama de aplicabilidade diversa', 'Nitrolux', false, 2);
INSERT INTO produto VALUES (DEFAULT, 'Disjuntor Monofásico ', 13.79, 'Desenvolvido Para Garantir A Segurança Da Instalação, Ele Preserva A Rede Elétrica E Seus Equipamentos Em Caso De Sobrecarga Ou Curto-Circuito', 'Tramontina', false, 3);
INSERT INTO produto VALUES (DEFAULT, 'Painel led', 16.19, 'Modernize seu ambiente interno, com um produto prático e versátil. O Painel Led da Fortec, produzido com tecnologia de ponta e os mais altos padrões de qualidade', 'Fortec', true, 2);
INSERT INTO produto VALUES (DEFAULT, 'Eletroduto Rígido', 11.09, 'O Eletroduto Rígido Amanco Soldável 25 MM 3M é aplicado em instalações prediais elétricas de baixa tensão', 'Amanco', true, 1);
INSERT INTO produto VALUES (DEFAULT, 'Curva Eletroduto', 3.99, 'A Curva Eletroduto Tigre Soldável Classe A 25 MM, foi desenvolvida para proporcionar mais qualidade e eficiência em instalações elétricas prediais de baixa tensão', 'Tigre', false, 3);
INSERT INTO produto VALUES (DEFAULT, 'Refletor Luminária Solar', 459.90, 'Se você está à procura de uma luminária potente e de qualidade para iluminar áreas externas, essa é a hora de conhecer a luminária solar integrada 1200 lúmens da ecoforce.', 'Ecoforce', True, 10);
INSERT INTO produto VALUES (DEFAULT, 'Transformador 2000VA Bivolt 110/220', 129.99, 'Produto Bivolt: Converte a tensão de 110V (127V) para 220V ou de 220 V para 110V (127 V). ', 'V & M', false, 17);


INSERT INTO ficha_tecnica VALUES (DEFAULT, 1, 'Codigo de barras', '7891435924558');
INSERT INTO ficha_tecnica VALUES (DEFAULT, 1, 'Material', 'Termoplastico');
INSERT INTO ficha_tecnica VALUES (DEFAULT, 2, 'Coleção', 'Lux');
INSERT INTO ficha_tecnica VALUES (DEFAULT, 2, 'Dimensões', '122 x 79 x 42mm');
INSERT INTO ficha_tecnica VALUES (DEFAULT, 3, 'Linha', 'FLEXSIL 750V');
INSERT INTO ficha_tecnica VALUES (DEFAULT, 3, 'Condutor', 'Fios de cobre');
INSERT INTO ficha_tecnica VALUES (DEFAULT, 4, 'Modelo', 'A-60');
INSERT INTO ficha_tecnica VALUES (DEFAULT, 4, 'Código', '1659');
INSERT INTO ficha_tecnica VALUES (DEFAULT, 5, 'Referência', '58011105');
INSERT INTO ficha_tecnica VALUES (DEFAULT, 5, 'Código de barras', '7891435966336');
INSERT INTO ficha_tecnica VALUES (DEFAULT, 6, 'Tipo', 'De embutir');
INSERT INTO ficha_tecnica VALUES (DEFAULT, 6, 'Formato', 'Quadrado');
INSERT INTO ficha_tecnica VALUES (DEFAULT, 6, 'Potência', '18w');
INSERT INTO ficha_tecnica VALUES (DEFAULT, 7, 'Ângulo', '90°');
INSERT INTO ficha_tecnica VALUES (DEFAULT, 7, 'Código de barras', '7897613333518');
INSERT INTO ficha_tecnica VALUES (DEFAULT, 7, 'Material', 'PVC');
INSERT INTO ficha_tecnica VALUES (DEFAULT, 8, 'Material', 'PVC');
INSERT INTO ficha_tecnica VALUES (DEFAULT, 8, 'Característica', 'rígido');
INSERT INTO ficha_tecnica VALUES (DEFAULT, 9, 'Altura', '5,8cm');
INSERT INTO ficha_tecnica VALUES (DEFAULT, 9, 'Largura', '23,2cm');
INSERT INTO ficha_tecnica VALUES (DEFAULT, 9, 'Cor', 'preto');
INSERT INTO ficha_tecnica VALUES (DEFAULT, 10, 'Frequência', '50/60 Hz');
INSERT INTO ficha_tecnica VALUES (DEFAULT, 10, 'Potência', '2000 VA');
INSERT INTO ficha_tecnica VALUES (DEFAULT, 10, 'Tensão Eletrica', 'Bivolt');

INSERT INTO produto_produto VALUES (1, 2);
INSERT INTO produto_produto VALUES (1, 3);
INSERT INTO produto_produto VALUES (2, 3);
INSERT INTO produto_produto VALUES (2, 1);
INSERT INTO produto_produto VALUES (3, 7);
INSERT INTO produto_produto VALUES (3, 2);
INSERT INTO produto_produto VALUES (4, 1);
INSERT INTO produto_produto VALUES (4, 9);
INSERT INTO produto_produto VALUES (5, 3);
INSERT INTO produto_produto VALUES (5, 10);
INSERT INTO produto_produto VALUES (6, 1);
INSERT INTO produto_produto VALUES (6, 8);
INSERT INTO produto_produto VALUES (7, 3);
INSERT INTO produto_produto VALUES (7, 10);
INSERT INTO produto_produto VALUES (8, 3);
INSERT INTO produto_produto VALUES (8, 7);
INSERT INTO produto_produto VALUES (9, 3);
INSERT INTO produto_produto VALUES (9, 4);
INSERT INTO produto_produto VALUES (10, 5);
INSERT INTO produto_produto VALUES (10, 7);

INSERT INTO imagem VALUES (DEFAULT, 1, '../aseets/images/img1');
INSERT INTO imagem VALUES (DEFAULT, 2, '../aseets/images/img2');
INSERT INTO imagem VALUES (DEFAULT, 3, '../aseets/images/img3');
INSERT INTO imagem VALUES (DEFAULT, 4, '../aseets/images/img4');
INSERT INTO imagem VALUES (DEFAULT, 5, '../aseets/images/img5');
INSERT INTO imagem VALUES (DEFAULT, 6, '../aseets/images/img6');
INSERT INTO imagem VALUES (DEFAULT, 7, '../aseets/images/img7');
INSERT INTO imagem VALUES (DEFAULT, 8, '../aseets/images/img8');
INSERT INTO imagem VALUES (DEFAULT, 9, '../aseets/images/img9');
INSERT INTO imagem VALUES (DEFAULT, 10, '../aseets/images/img10');

INSERT INTO compra VALUES (DEFAULT, 3, '18-03-2022', '19-03-2022');
INSERT INTO compra VALUES (DEFAULT, 3, '18-11-2021', '19-11-2021');
INSERT INTO compra VALUES (DEFAULT, 2, '01-04-2020', '02-05-2020');
INSERT INTO compra VALUES (DEFAULT, 5, '16-05-2022', '17-05-2022');
INSERT INTO compra VALUES (DEFAULT, 6, '30-11-2021', '01-12-2021');
INSERT INTO compra VALUES (DEFAULT, 8, '19-09-2022', '20-09-2022');
INSERT INTO compra VALUES (DEFAULT, 1, '24-06-2019', '25-06-2019');
INSERT INTO compra VALUES (DEFAULT, 8, '15-08-2022', '16-08-2022');
INSERT INTO compra VALUES (DEFAULT, 10, '15-03-2021', '16-03-2021');
INSERT INTO compra VALUES (DEFAULT, 7, '19-10-2020', '20-10-2020');

INSERT INTO compra_produto VALUES (1, 1, 3);
INSERT INTO compra_produto VALUES (1, 3, 1);
INSERT INTO compra_produto VALUES (1, 4, 3);
INSERT INTO compra_produto VALUES (2, 3, 1);
INSERT INTO compra_produto VALUES (2, 7, 2);
INSERT INTO compra_produto VALUES (3, 1, 3);
INSERT INTO compra_produto VALUES (4, 2, 5);
INSERT INTO compra_produto VALUES (4, 3, 2);
INSERT INTO compra_produto VALUES (4, 4, 4);
INSERT INTO compra_produto VALUES (4, 5, 7);
INSERT INTO compra_produto VALUES (5, 6, 2);
INSERT INTO compra_produto VALUES (5, 7, 8);
INSERT INTO compra_produto VALUES (6, 8, 2);
INSERT INTO compra_produto VALUES (6, 2, 1);
INSERT INTO compra_produto VALUES (7, 1, 2);
INSERT INTO compra_produto VALUES (8, 4, 3);

/*
SELECT * FROM cliente;
SELECT * FROM endereco;
SELECT * FROM categoria;
SELECT * FROM subcategoria;
SELECT * FROM produto;
SELECT * FROM ficha_tecnica;
SELECT * FROM produto_produto;
SELECT * FROM imagem;
SELECT * FROM compra;
SELECT * FROM compra_produto;
*/